feat(fullstack): fixing github deploy client and frontend

diff --git a/.github/workflows/deploy-client.yml b/.github/workflows/deploy-client.yml
--- a/.github/workflows/deploy-client.yml
+++ b/.github/workflows/deploy-client.yml
@@ -1,58 +1,72 @@
-# name: Deploy flexcars-client to Amazon EKS with Rollback
+name: Deploy flexcars-client to Amazon EKS with Rollback
 
-# on:
-#   push:
-#     branches:
-#       - main
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - develop
+jobs:
+  deploy:
+    name: Deploy flexcars-client to EKS
+    runs-on: ubuntu-latest
+    environment: production
 
-# jobs:
-#   deploy:
-#     name: Deploy flexcars-client to EKS
-#     runs-on: ubuntu-latest
+    permissions:
+      id-token: write 
+      contents: read 
 
-#     steps:
-#       - name: Checkout Code
-#         uses: actions/checkout@v4
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-#       - name: Configure AWS Credentials
-#         uses: aws-actions/configure-aws-credentials@v2
-#         with:
-#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#           aws-region: eu-west-3
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::715221148096:role/github-runner-role
+          aws-region: eu-west-3
+          audience: sts.amazonaws.com
+          mask-aws-account-id: 'false'
 
-#       - name: Authenticate with AWS ECR
-#         run: |
-#           aws ecr get-login-password --region eu-west-3 | \
-#           docker login --username AWS --password-stdin ${{ secrets.FLEXCARS_CLIENT_ECR_REGISTRY }}
+      - name: Authenticate with AWS ECR
+        run: |
+          aws ecr get-login-password --region eu-west-3 | \
+          docker login --username AWS --password-stdin 715221148096.dkr.ecr.eu-west-3.amazonaws.com
 
-#       - name: Build and Push Docker Image
-#         run: |
-#           IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
-#           docker build -t ${{ secrets.FLEXCARS_CLIENT_ECR_REGISTRY }}/${{ secrets.FLEXCARS_CLIENT_ECR_REPOSITORY }}:$IMAGE_TAG .
-#           docker push ${{ secrets.FLEXCARS_CLIENT_ECR_REGISTRY }}/${{ secrets.FLEXCARS_CLIENT_ECR_REPOSITORY }}:$IMAGE_TAG
-#           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+      - name: Build and Push Docker Image
+        run: |
+          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
+          docker build -f src/flexcars-client/Dockerfile \
+            --build-arg NEXT_PUBLIC_API_URL="http://a64a8da2a07e24b938c9c1007cb63f60-1364088154.eu-west-3.elb.amazonaws.com" \
+            --build-arg NEXTAUTH_SECRET="om49e451tlnud88l6c3k4gh798k0fbj2" \
+            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_51RiuDzQtpYBxzRsNqTQbdxgZUKAUOI3w3gFwtQ64rRRrtXDSLX8fQmzc9Hvh7y5m66bHIL2dqwmhyEmHP7pxH8vs00BHp5SYDC" \
+            -t 715221148096.dkr.ecr.eu-west-3.amazonaws.com/flexcars-client:$IMAGE_TAG src/flexcars-client
+          docker push 715221148096.dkr.ecr.eu-west-3.amazonaws.com/flexcars-client:$IMAGE_TAG
+          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
 
-#       - name: Update kubeconfig for EKS and create ECR secret
-#         run: |
-#           aws eks --region eu-west-3 update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
-#           kubectl create secret docker-registry frontend-ecr-secret --docker-server=${{ secrets.FLEXCARS_CLIENT_ECR_REGISTRY }} --docker-username=AWS --docker-password=$(aws ecr get-login-password --region eu-west-3)
+      - name: Update kubeconfig for EKS and create ECR secret
+        run: |
+          aws eks --region eu-west-3 update-kubeconfig --name eks-cluster
+          kubectl delete secret frontend-ecr-secret --ignore-not-found
+          kubectl create secret docker-registry client-ecr-secret --docker-server=715221148096.dkr.ecr.eu-west-3.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region eu-west-3)
 
-#       - name: Get Previous Image Tag (For Rollback)
-#         id: get-prev-image
-#         run: |
-#           PREV_IMAGE=$(kubectl get deployment ${{ secrets.FLEXCARS_CLIENT_DEPLOYMENT_NAME }} -o=jsonpath='{.spec.template.spec.containers[0].image}')
-#           echo "PREV_IMAGE=$PREV_IMAGE" >> $GITHUB_ENV
+      - name: Get Previous Image Tag (For Rollback)
+        id: get-prev-image
+        if: failure()
+        run: |
+          PREV_IMAGE=$(kubectl get deployment flexcars-client -o=jsonpath='{.spec.template.spec.containers[0].image}')
+          echo "PREV_IMAGE=$PREV_IMAGE" >> $GITHUB_ENV
 
-#       - name: Deploy to Kubernetes
-#         id: deploy
-#         run: |
-#           kubectl set image deployment/${{ secrets.FLEXCARS_CLIENT_DEPLOYMENT_NAME }} ${{ secrets.FLEXCARS_CLIENT_APP_NAME }}=${{ secrets.FLEXCARS_CLIENT_ECR_REGISTRY }}/${{ secrets.FLEXCARS_CLIENT_ECR_REPOSITORY }}:$IMAGE_TAG
-#           kubectl rollout status deployment/${{ secrets.FLEXCARS_CLIENT_DEPLOYMENT_NAME }} || exit 1
+      - name: Deploy to Kubernetes
+        id: deploy
+        run: |
+          kubectl set image deployment/flexcars-client flexcars-client=715221148096.dkr.ecr.eu-west-3.amazonaws.com/flexcars-client:$IMAGE_TAG
+          kubectl rollout status deployment/flexcars-client || exit 1
 
-#       - name: Rollback on Failure
-#         if: failure()
-#         run: |
-#           echo "Deployment failed! Rolling back to previous stable image..."
-#           kubectl set image deployment/${{ secrets.FLEXCARS_CLIENT_DEPLOYMENT_NAME }} ${{ secrets.FLEXCARS_CLIENT_APP_NAME }}=$PREV_IMAGE
-#           kubectl rollout status deployment/${{ secrets.FLEXCARS_CLIENT_DEPLOYMENT_NAME }}
+      - name: Rollback on Failure
+        if: failure()
+        run: |
+          echo "Deployment failed! Rolling back to previous stable image..."
+          kubectl set image deployment/flexcars-client flexcars-client=$PREV_IMAGE
+          kubectl rollout status deployment/flexcars-client || exit 1
